### ISSUE TITLE
Does not work with version 2024.1.0

### ISSUE THREAD

**Issue by Furrypaw** [jariz/homeassistant-basestation#12]
After updating to 2024.1.0 I seemingly get following error:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:894
First occurred: 6:52:39 PM (144 occurrences)
Last logged: 7:17:07 PM

Update for switch.lhb_1 fails
Update for switch.lhb_2 fails
Update for switch.lhb_3 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 894, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1212, in async_device_update
    await self.async_update()
  File "/config/custom_components/basestation/switch.py", line 71, in async_update
    async with BleakClient(self.get_ble_device()) as client:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/basestation/switch.py", line 75, in get_ble_device
    return bluetooth.async_ble_device_from_address(self._hass, self._mac)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/api.py", line 92, in async_ble_device_from_address
    return _get_manager(hass).async_ble_device_from_address(address, connectable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 'address' has incorrect type (expected str, got NodeStrClass)

```

**Comment by jariz** [comment]
I'm open to PR's, but personally not really using this anymore, so don't expect a whole lot from me. Probably better to use a ESP32 anyway.
