### ISSUE TITLE
Not working on Raspberry Pi? "No device found for address None"

### ISSUE THREAD

**Issue by codingcatgirl** [jariz/homeassistant-basestation#8]
I'm using Home Assistant OS on my Raspberry Pi. I set it up with two base stations, like described in the readme.

Result: When i flip the switch, i get the following error:

```
[547203249152] No device found for address None

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/basestation/switch.py", line 63, in async_turn_on
    async with BleakClient(self.get_ble_device()) as client:
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 354, in __aenter__
    await self.connect()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 283, in connect
    self._async_get_backend() or await self._async_get_fallback_backend()
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/models.py", line 320, in _async_get_backend
    raise BleakError(f"No device found for address {address}")
bleak.exc.BleakError: No device found for address None
```

Should this work on a Pi? I have no idea why it says `address None`, i triple checked the mac addresses and they are definitely correct, i copied them right out of the Light House Control app for Android.

Everything's up to date, i might add.

How do i fix this?

**Comment by codingcatgirl** [comment]
I mean… there's not much to say about the config

```yml
switch steamvr:
  - platform: basestation
    mac: "C2:9F:FA:XX:XX:XX" (correct mac address)
    name: "VR Basestation Back"
  - platform: basestation
    mac: "C3:65:AC:XX:XX:XX" (correct mac address)
    name: "VR Basestation Front"
```

**Comment by jesterod** [comment]
Im having the same issue and used your exact example code with the macs changed to mine
